#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OdvezAuto.Droid.Resource", IsApplication=true)]

namespace OdvezAuto.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_logout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060022
			public const int AddCarButton = 2131099682;
			
			// aapt resource value: 0x7f060000
			public const int BackButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int BrandAdd = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int BrandDetail = 2131099664;
			
			// aapt resource value: 0x7f060019
			public const int BrandEdit = 2131099673;
			
			// aapt resource value: 0x7f06000d
			public const int BrandTypeList = 2131099661;
			
			// aapt resource value: 0x7f060018
			public const int BuyButton = 2131099672;
			
			// aapt resource value: 0x7f060020
			public const int CarList = 2131099680;
			
			// aapt resource value: 0x7f06000f
			public const int EditButton = 2131099663;
			
			// aapt resource value: 0x7f060004
			public const int KilometersAdd = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int KilometersDetail = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int KilometersEdit = 2131099676;
			
			// aapt resource value: 0x7f060009
			public const int LoadedPictureImageView = 2131099657;
			
			// aapt resource value: 0x7f060021
			public const int LogOutButton = 2131099681;
			
			// aapt resource value: 0x7f060025
			public const int LoginButton = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int Password = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int PictureBig = 2131099686;
			
			// aapt resource value: 0x7f060008
			public const int PictureLoadButton = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int PictureUrlEditText = 2131099655;
			
			// aapt resource value: 0x7f060016
			public const int PictureZoom = 2131099670;
			
			// aapt resource value: 0x7f060005
			public const int PowerAdd = 2131099653;
			
			// aapt resource value: 0x7f060014
			public const int PowerDetail = 2131099668;
			
			// aapt resource value: 0x7f06001d
			public const int PowerEdit = 2131099677;
			
			// aapt resource value: 0x7f06000a
			public const int PriceAdd = 2131099658;
			
			// aapt resource value: 0x7f060017
			public const int PriceDetail = 2131099671;
			
			// aapt resource value: 0x7f06001f
			public const int PriceEdit = 2131099679;
			
			// aapt resource value: 0x7f06000e
			public const int PriceList = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int RowImageView = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int SellButton = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int StateAdd = 2131099651;
			
			// aapt resource value: 0x7f060012
			public const int StateDetail = 2131099666;
			
			// aapt resource value: 0x7f06001b
			public const int StateEdit = 2131099675;
			
			// aapt resource value: 0x7f060006
			public const int TorqueAdd = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int TorqueDetail = 2131099669;
			
			// aapt resource value: 0x7f06001e
			public const int TorqueEdit = 2131099678;
			
			// aapt resource value: 0x7f060002
			public const int TypeAdd = 2131099650;
			
			// aapt resource value: 0x7f060011
			public const int TypeDetail = 2131099665;
			
			// aapt resource value: 0x7f06001a
			public const int TypeEdit = 2131099674;
			
			// aapt resource value: 0x7f060023
			public const int Username = 2131099683;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Add = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CarListRow = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Detail = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Edit = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int List = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int LoginScreen = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Zoom = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Logo = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
